---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ombi
  labels:
    app: ombi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ombi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ombi
    spec:
      containers:
      - name: ombi
        imagePullPolicy: "Always"
#        image: linuxserver/ombi:latest
        image: linuxserver/ombi:4.29.0-development
        ports:
        - name: http
          containerPort: 3579
          protocol: TCP
        env:
        - name: TZ
          value: "America/Denver"
        - name: PUID
          value: "1000"
        - name: GUID
          value: "1000"
        volumeMounts:
        - name: k8s-pv02
          mountPath: /config
          subPath: ombi/config
      volumes:
      - name: k8s-pv02
        persistentVolumeClaim:
          claimName: synology-k8s-pv02
